/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.number().default(0).nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    isValidated: z.boolean().default(false),
    emailToken: z.string(),
    timeStamp: z.coerce.date(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean().nullish(),
    isPublic: z.boolean().nullish(),
    isDeleted: z.number().nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    isValidated: z.boolean(),
    emailToken: z.string(),
    timeStamp: z.coerce.date(),
}
).strict();

/**
 * `AccountValidation` schema excluding foreign keys and relations.
 */
export const AccountValidationScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `AccountValidation` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const AccountValidationSchema = AccountValidationScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const AccountValidationPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const AccountValidationPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean().nullish(),
    isPublic: z.boolean().nullish(),
    isDeleted: z.union([z.number().nullish(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    isValidated: z.boolean(),
    emailToken: z.string(),
    timeStamp: z.coerce.date()
}).partial().passthrough();


/**
 * `AccountValidation` schema for create operations excluding foreign keys and relations.
 */
export const AccountValidationCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true, isValidated: true
});


/**
 * `AccountValidation` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const AccountValidationCreateSchema = baseSchemaWithoutDefaults.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true, isValidated: true
});


/**
 * `AccountValidation` schema for update operations excluding foreign keys and relations.
 */
export const AccountValidationUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `AccountValidation` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const AccountValidationUpdateSchema = AccountValidationUpdateScalarSchema;

