/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    key: z.string(),
    uuid: z.string(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    key: z.string(),
    uuid: z.string(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
    Scopes: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    userId: z.string(),
}
);

/**
 * `ApiKey` schema excluding foreign keys and relations.
 */
export const ApiKeyScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `ApiKey` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ApiKeySchema = ApiKeyScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ApiKeyPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ApiKeyPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    key: z.string(),
    uuid: z.string()
}).partial().passthrough();


/**
 * `ApiKey` schema for create operations excluding foreign keys and relations.
 */
export const ApiKeyCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `ApiKey` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ApiKeyCreateSchema = ApiKeyCreateScalarSchema.merge(fkSchema);


/**
 * `ApiKey` schema for update operations excluding foreign keys and relations.
 */
export const ApiKeyUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `ApiKey` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ApiKeyUpdateSchema = ApiKeyUpdateScalarSchema.merge(fkSchema.partial());

