/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    domain: z.string(),
    allowed: z.boolean(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    domain: z.string(),
    allowed: z.boolean(),
}
).strict();

/**
 * `AppEmailDomain` schema excluding foreign keys and relations.
 */
export const AppEmailDomainScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `AppEmailDomain` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const AppEmailDomainSchema = AppEmailDomainScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const AppEmailDomainPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const AppEmailDomainPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    domain: z.string(),
    allowed: z.boolean()
}).partial().passthrough();


/**
 * `AppEmailDomain` schema for create operations excluding foreign keys and relations.
 */
export const AppEmailDomainCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `AppEmailDomain` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const AppEmailDomainCreateSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `AppEmailDomain` schema for update operations excluding foreign keys and relations.
 */
export const AppEmailDomainUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `AppEmailDomain` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const AppEmailDomainUpdateSchema = AppEmailDomainUpdateScalarSchema;

