/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.number().default(0).nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    orderComment: z.number(),
    content: z.string().nullish(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean().nullish(),
    isPublic: z.boolean().nullish(),
    isDeleted: z.number().nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    orderComment: z.number(),
    content: z.string().nullish(),
}
).strict();
const relationSchema = z.object({
    post: z.record(z.string(), z.unknown()),
    author: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    postId: z.string(),
    authorId: z.string(),
}
);

/**
 * `Comment` schema excluding foreign keys and relations.
 */
export const CommentScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Comment` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const CommentSchema = CommentScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const CommentPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const CommentPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean().nullish(),
    isPublic: z.boolean().nullish(),
    isDeleted: z.union([z.number().nullish(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    orderComment: z.union([z.number(), z.record(z.string(), z.unknown())]),
    content: z.string().nullish()
}).partial().passthrough();


/**
 * `Comment` schema for create operations excluding foreign keys and relations.
 */
export const CommentCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Comment` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const CommentCreateSchema = CommentCreateScalarSchema.merge(fkSchema);


/**
 * `Comment` schema for update operations excluding foreign keys and relations.
 */
export const CommentUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `Comment` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const CommentUpdateSchema = CommentUpdateScalarSchema.merge(fkSchema.partial());

