/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean().default(false),
    name: z.string(),
    storageName: z.string(),
    type: z.string().nullish(),
    data: z.string().nullish(),
    size: z.number().nullish(),
    isArchived: z.coerce.date().nullish(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean(),
    name: z.string(),
    storageName: z.string(),
    type: z.string().nullish(),
    data: z.string().nullish(),
    size: z.number().nullish(),
    isArchived: z.coerce.date().nullish(),
}
).strict();
const relationSchema = z.object({
    owner: z.record(z.string(), z.unknown()),
    org: z.record(z.string(), z.unknown()),
    groups: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    ownerId: z.string(),
    orgId: z.string(),
}
);

/**
 * `File` schema excluding foreign keys and relations.
 */
export const FileScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `File` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const FileSchema = FileScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const FilePrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const FilePrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean(),
    name: z.string(),
    storageName: z.string(),
    type: z.string().nullish(),
    data: z.string().nullish(),
    size: z.union([z.number().nullish(), z.record(z.string(), z.unknown())]),
    isArchived: z.coerce.date().nullish()
}).partial().passthrough();


/**
 * `File` schema for create operations excluding foreign keys and relations.
 */
export const FileCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isDeleted: true, isPublic: true
});


/**
 * `File` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const FileCreateSchema = FileCreateScalarSchema.merge(fkSchema);


/**
 * `File` schema for update operations excluding foreign keys and relations.
 */
export const FileUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `File` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const FileUpdateSchema = FileUpdateScalarSchema.merge(fkSchema.partial());

