/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    orderGroup: z.number(),
    name: z.string(),
    description: z.string().nullish(),
    isActiv: z.coerce.date().nullish(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    orderGroup: z.number(),
    name: z.string(),
    description: z.string().nullish(),
    isActiv: z.coerce.date().nullish(),
}
).strict();
const relationSchema = z.object({
    Users: z.array(z.unknown()).optional(),
    Tasks: z.array(z.unknown()).optional(),
    Todos: z.array(z.unknown()).optional(),
    Posts: z.array(z.unknown()).optional(),
    Files: z.array(z.unknown()).optional(),
    org: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    orgId: z.string(),
}
);

/**
 * `Group` schema excluding foreign keys and relations.
 */
export const GroupScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Group` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const GroupSchema = GroupScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const GroupPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const GroupPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    orderGroup: z.union([z.number(), z.record(z.string(), z.unknown())]),
    name: z.string(),
    description: z.string().nullish(),
    isActiv: z.coerce.date().nullish()
}).partial().passthrough();


/**
 * `Group` schema for create operations excluding foreign keys and relations.
 */
export const GroupCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Group` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const GroupCreateSchema = GroupCreateScalarSchema.merge(fkSchema);


/**
 * `Group` schema for update operations excluding foreign keys and relations.
 */
export const GroupUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `Group` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const GroupUpdateSchema = GroupUpdateScalarSchema.merge(fkSchema.partial());

