/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    type: z.string(),
    url: z.string(),
    associated_id: z.string(),
    sequence: z.number(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    type: z.string(),
    url: z.string(),
    associated_id: z.string(),
    sequence: z.number(),
}
).strict();

/**
 * `Image` schema excluding foreign keys and relations.
 */
export const ImageScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Image` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ImageSchema = ImageScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ImagePrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ImagePrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    type: z.string(),
    url: z.string(),
    associated_id: z.string(),
    sequence: z.union([z.number(), z.record(z.string(), z.unknown())])
}).partial().passthrough();


/**
 * `Image` schema for create operations excluding foreign keys and relations.
 */
export const ImageCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Image` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ImageCreateSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Image` schema for update operations excluding foreign keys and relations.
 */
export const ImageUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `Image` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ImageUpdateSchema = ImageUpdateScalarSchema;

