/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    email: z.string().email(),
    description: z.string().nullish(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    email: z.string().email(),
    description: z.string().nullish(),
}
).strict();
const relationSchema = z.object({
    org: z.record(z.string(), z.unknown()).optional(),
    OrgEmailUseTos: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    orgId: z.string(),
}
);

/**
 * `OrgEmail` schema excluding foreign keys and relations.
 */
export const OrgEmailScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `OrgEmail` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const OrgEmailSchema = OrgEmailScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const OrgEmailPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const OrgEmailPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    email: z.string().email(),
    description: z.string().nullish()
}).partial().passthrough();


/**
 * `OrgEmail` schema for create operations excluding foreign keys and relations.
 */
export const OrgEmailCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `OrgEmail` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const OrgEmailCreateSchema = OrgEmailCreateScalarSchema.merge(fkSchema);


/**
 * `OrgEmail` schema for update operations excluding foreign keys and relations.
 */
export const OrgEmailUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `OrgEmail` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const OrgEmailUpdateSchema = OrgEmailUpdateScalarSchema.merge(fkSchema.partial());

