/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean().default(false),
    orderPost: z.number().nullish(),
    title: z.string(),
    content: z.string().nullish(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean(),
    orderPost: z.number().nullish(),
    title: z.string(),
    content: z.string().nullish(),
}
).strict();
const relationSchema = z.object({
    owner: z.record(z.string(), z.unknown()),
    org: z.record(z.string(), z.unknown()),
    groups: z.array(z.unknown()).optional(),
    Categories: z.array(z.unknown()).optional(),
    Comments: z.array(z.unknown()).optional(),
    LikedBys: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    ownerId: z.string(),
    orgId: z.string(),
}
);

/**
 * `Post` schema excluding foreign keys and relations.
 */
export const PostScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Post` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const PostSchema = PostScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const PostPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const PostPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean(),
    orderPost: z.union([z.number().nullish(), z.record(z.string(), z.unknown())]),
    title: z.string(),
    content: z.string().nullish()
}).partial().passthrough();


/**
 * `Post` schema for create operations excluding foreign keys and relations.
 */
export const PostCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isDeleted: true, isPublic: true
});


/**
 * `Post` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const PostCreateSchema = PostCreateScalarSchema.merge(fkSchema);


/**
 * `Post` schema for update operations excluding foreign keys and relations.
 */
export const PostUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `Post` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const PostUpdateSchema = PostUpdateScalarSchema.merge(fkSchema.partial());

