/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';
const baseSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    user_id: z.string(),
    post_id: z.string(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
    post: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
}
);

/**
 * `PostLike` schema excluding foreign keys and relations.
 */
export const PostLikeScalarSchema = baseSchema;


/**
 * `PostLike` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const PostLikeSchema = PostLikeScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const PostLikePrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const PostLikePrismaUpdateSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `PostLike` schema for create operations excluding foreign keys and relations.
 */
export const PostLikeCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    createdAt: true, updatedAt: true
});


/**
 * `PostLike` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const PostLikeCreateSchema = PostLikeCreateScalarSchema.merge(fkSchema);


/**
 * `PostLike` schema for update operations excluding foreign keys and relations.
 */
export const PostLikeUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `PostLike` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const PostLikeUpdateSchema = PostLikeUpdateScalarSchema.merge(fkSchema.partial());

