/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    orderProfile: z.number(),
    bio: z.string(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.number(),
    isDeletedDT: z.coerce.date().nullish(),
    orderProfile: z.number(),
    bio: z.string(),
}
).strict();
const relationSchema = z.object({
    Users: z.array(z.unknown()).optional(),
}
);

/**
 * `Profile` schema excluding foreign keys and relations.
 */
export const ProfileScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Profile` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ProfileSchema = ProfileScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ProfilePrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ProfilePrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean(),
    isPublic: z.boolean(),
    isDeleted: z.union([z.number(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    orderProfile: z.union([z.number(), z.record(z.string(), z.unknown())]),
    bio: z.string()
}).partial().passthrough();


/**
 * `Profile` schema for create operations excluding foreign keys and relations.
 */
export const ProfileCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Profile` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ProfileCreateSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Profile` schema for update operations excluding foreign keys and relations.
 */
export const ProfileUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `Profile` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ProfileUpdateSchema = ProfileUpdateScalarSchema;

