/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.number().default(0).nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    caption: z.string(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean().nullish(),
    isPublic: z.boolean().nullish(),
    isDeleted: z.number().nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    caption: z.string(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    user_id: z.string(),
}
);

/**
 * `Story` schema excluding foreign keys and relations.
 */
export const StoryScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Story` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const StorySchema = StoryScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const StoryPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const StoryPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    published: z.boolean().nullish(),
    isPublic: z.boolean().nullish(),
    isDeleted: z.union([z.number().nullish(), z.record(z.string(), z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    caption: z.string()
}).partial().passthrough();


/**
 * `Story` schema for create operations excluding foreign keys and relations.
 */
export const StoryCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Story` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const StoryCreateSchema = StoryCreateScalarSchema.merge(fkSchema);


/**
 * `Story` schema for update operations excluding foreign keys and relations.
 */
export const StoryUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `Story` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const StoryUpdateSchema = StoryUpdateScalarSchema.merge(fkSchema.partial());

