/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    userId: z.string(),
    taskId: z.string(),
    isAuthor: z.boolean().default(true),
    isAssigned: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    comment: z.string(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    userId: z.string(),
    taskId: z.string(),
    isAuthor: z.boolean(),
    isAssigned: z.boolean(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    comment: z.string(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
    task: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    userId: z.string(),
    taskId: z.string(),
}
);

/**
 * `UserTaskLink` schema excluding foreign keys and relations.
 */
export const UserTaskLinkScalarSchema = baseSchema;


/**
 * `UserTaskLink` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserTaskLinkSchema = UserTaskLinkScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserTaskLinkPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserTaskLinkPrismaUpdateSchema = z.object({
    userId: z.string(),
    taskId: z.string(),
    isAuthor: z.boolean(),
    isAssigned: z.boolean(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    comment: z.string()
}).partial().passthrough();


/**
 * `UserTaskLink` schema for create operations excluding foreign keys and relations.
 */
export const UserTaskLinkCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    isAuthor: true, isAssigned: true, createdAt: true, updatedAt: true
});


/**
 * `UserTaskLink` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserTaskLinkCreateSchema = UserTaskLinkCreateScalarSchema.merge(fkSchema);


/**
 * `UserTaskLink` schema for update operations excluding foreign keys and relations.
 */
export const UserTaskLinkUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `UserTaskLink` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserTaskLinkUpdateSchema = UserTaskLinkUpdateScalarSchema.merge(fkSchema.partial());

