/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    userId: z.string(),
    todoId: z.string(),
    isAuthor: z.boolean().default(true),
    isAssigned: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    comment: z.string(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    userId: z.string(),
    todoId: z.string(),
    isAuthor: z.boolean(),
    isAssigned: z.boolean(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    comment: z.string(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
    todo: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    userId: z.string(),
    todoId: z.string(),
}
);

/**
 * `UserTodoLink` schema excluding foreign keys and relations.
 */
export const UserTodoLinkScalarSchema = baseSchema;


/**
 * `UserTodoLink` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserTodoLinkSchema = UserTodoLinkScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserTodoLinkPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserTodoLinkPrismaUpdateSchema = z.object({
    userId: z.string(),
    todoId: z.string(),
    isAuthor: z.boolean(),
    isAssigned: z.boolean(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    comment: z.string()
}).partial().passthrough();


/**
 * `UserTodoLink` schema for create operations excluding foreign keys and relations.
 */
export const UserTodoLinkCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    isAuthor: true, isAssigned: true, createdAt: true, updatedAt: true
});


/**
 * `UserTodoLink` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserTodoLinkCreateSchema = UserTodoLinkCreateScalarSchema.merge(fkSchema);


/**
 * `UserTodoLink` schema for update operations excluding foreign keys and relations.
 */
export const UserTodoLinkUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `UserTodoLink` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserTodoLinkUpdateSchema = UserTodoLinkUpdateScalarSchema.merge(fkSchema.partial());

