/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    pwdHash: z.string().nullish(),
    salt: z.string().nullish(),
    isAdmin: z.boolean().default(false).nullish(),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    id: z.number(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    pwdHash: z.string().nullish(),
    salt: z.string().nullish(),
    isAdmin: z.boolean().nullish(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    userId: z.string(),
}
);

/**
 * `UserSecret` schema excluding foreign keys and relations.
 */
export const UserSecretScalarSchema = baseSchema.omit({
    pwdHash: true,
});


/**
 * `UserSecret` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserSecretSchema = UserSecretScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserSecretPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserSecretPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.string(), z.unknown())]),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
    pwdHash: z.string().nullish(),
    salt: z.string().nullish(),
    isAdmin: z.boolean().nullish()
}).partial().passthrough();


/**
 * `UserSecret` schema for create operations excluding foreign keys and relations.
 */
export const UserSecretCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    id: true, createdAt: true, updatedAt: true, isAdmin: true
});


/**
 * `UserSecret` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserSecretCreateSchema = UserSecretCreateScalarSchema.merge(fkSchema);


/**
 * `UserSecret` schema for update operations excluding foreign keys and relations.
 */
export const UserSecretUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `UserSecret` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserSecretUpdateSchema = UserSecretUpdateScalarSchema.merge(fkSchema.partial());

