/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';
const baseSchema = z.object({
    user_id: z.string(),
    follower_id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
}
).strict();
const baseSchemaWithoutDefaults = z.object({
    user_id: z.string(),
    follower_id: z.string(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.string(), z.unknown()),
    follower: z.record(z.string(), z.unknown()),
}
);
const fkSchema = z.object({
    user_id: z.string(),
    follower_id: z.string(),
}
);

/**
 * `UserFollower` schema excluding foreign keys and relations.
 */
export const UserFollowerScalarSchema = baseSchema;


/**
 * `UserFollower` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserFollowerSchema = UserFollowerScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserFollowerPrismaCreateSchema = baseSchemaWithoutDefaults.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserFollowerPrismaUpdateSchema = z.object({
    user_id: z.string(),
    follower_id: z.string(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `UserFollower` schema for create operations excluding foreign keys and relations.
 */
export const UserFollowerCreateScalarSchema = baseSchemaWithoutDefaults.partial({
    createdAt: true, updatedAt: true
});


/**
 * `UserFollower` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserFollowerCreateSchema = UserFollowerCreateScalarSchema.merge(fkSchema);


/**
 * `UserFollower` schema for update operations excluding foreign keys and relations.
 */
export const UserFollowerUpdateScalarSchema = baseSchemaWithoutDefaults.partial();


/**
 * `UserFollower` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserFollowerUpdateSchema = UserFollowerUpdateScalarSchema.merge(fkSchema.partial());

