/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

export * from '../../generated/prisma_new_client/models';
export * from './json-types';
