/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    name: z.string(),
    value: z.string(),
    utility: z.string(),
}
).strict();

/**
 * `ConfigParam` schema excluding foreign keys and relations.
 */
export const ConfigParamScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `ConfigParam` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ConfigParamSchema = ConfigParamScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ConfigParamPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ConfigParamPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    name: z.string(),
    value: z.string(),
    utility: z.string()
}).partial().passthrough();


/**
 * `ConfigParam` schema for create operations excluding foreign keys and relations.
 */
export const ConfigParamCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `ConfigParam` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ConfigParamCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `ConfigParam` schema for update operations excluding foreign keys and relations.
 */
export const ConfigParamUpdateScalarSchema = baseSchema.partial();


/**
 * `ConfigParam` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ConfigParamUpdateSchema = ConfigParamUpdateScalarSchema;

