/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.number().default(0).nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    name: z.string(),
    description: z.string().nullish(),
    address: z.any().nullish(),
    emailITAdmin: z.string().email(),
    webSite: z.string().nullish(),
}
).strict();
const relationSchema = z.object({
    OrgEmails: z.array(z.unknown()).optional(),
    OrgDomains: z.array(z.unknown()).optional(),
    mainOrg: z.record(z.unknown()).optional(),
    OrgEntity: z.array(z.unknown()).optional(),
    Members: z.array(z.unknown()).optional(),
    Posts: z.array(z.unknown()).optional(),
    Groups: z.array(z.unknown()).optional(),
    Files: z.array(z.unknown()).optional(),
    Tasks: z.array(z.unknown()).optional(),
    Todos: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    mainOrgId: z.string().nullish(),
}
);

/**
 * `Organization` schema excluding foreign keys and relations.
 */
export const OrganizationScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Organization` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const OrganizationSchema = OrganizationScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const OrganizationPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const OrganizationPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.union([z.number().default(0).nullish(), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    name: z.string(),
    description: z.string().nullish(),
    address: z.any().nullish(),
    emailITAdmin: z.string().email(),
    webSite: z.string().nullish()
}).partial().passthrough();


/**
 * `Organization` schema for create operations excluding foreign keys and relations.
 */
export const OrganizationCreateScalarSchema = baseSchema.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Organization` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const OrganizationCreateSchema = OrganizationCreateScalarSchema.merge(fkSchema);


/**
 * `Organization` schema for update operations excluding foreign keys and relations.
 */
export const OrganizationUpdateScalarSchema = baseSchema.partial();


/**
 * `Organization` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const OrganizationUpdateSchema = OrganizationUpdateScalarSchema.merge(fkSchema.partial());

