/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    userId: z.string(),
    tokenId: z.string(),
}
).strict();

/**
 * `RefreshToken` schema excluding foreign keys and relations.
 */
export const RefreshTokenScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `RefreshToken` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const RefreshTokenSchema = RefreshTokenScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const RefreshTokenPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const RefreshTokenPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    userId: z.string(),
    tokenId: z.string()
}).partial().passthrough();


/**
 * `RefreshToken` schema for create operations excluding foreign keys and relations.
 */
export const RefreshTokenCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `RefreshToken` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const RefreshTokenCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `RefreshToken` schema for update operations excluding foreign keys and relations.
 */
export const RefreshTokenUpdateScalarSchema = baseSchema.partial();


/**
 * `RefreshToken` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const RefreshTokenUpdateSchema = RefreshTokenUpdateScalarSchema;

