/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { TaskState } from '../../../../generated/prisma_new_client/client';
import { TaskStateSchema } from '../enums/TaskState.schema';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean().default(false),
    orderTask: z.number(),
    title: z.string(),
    content: z.string().nullish(),
    taskState: TaskStateSchema,
}
).strict();
const relationSchema = z.object({
    owner: z.record(z.unknown()),
    org: z.record(z.unknown()),
    groups: z.array(z.unknown()).optional(),
    mainTask: z.record(z.unknown()).optional(),
    SubTasks: z.array(z.unknown()).optional(),
    Users: z.array(z.unknown()).optional(),
    todo: z.record(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    ownerId: z.string(),
    orgId: z.string(),
    mainTaskId: z.string().nullish(),
    todoId: z.string().nullish(),
}
);

/**
 * `Task` schema excluding foreign keys and relations.
 */
export const TaskScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Task` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const TaskSchema = TaskScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const TaskPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const TaskPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean().default(false),
    orderTask: z.union([z.number(), z.record(z.unknown())]),
    title: z.string(),
    content: z.string().nullish(),
    taskState: TaskStateSchema
}).partial().passthrough();


/**
 * `Task` schema for create operations excluding foreign keys and relations.
 */
export const TaskCreateScalarSchema = baseSchema.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isDeleted: true, isPublic: true, taskState: true
});


/**
 * `Task` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const TaskCreateSchema = TaskCreateScalarSchema.merge(fkSchema);


/**
 * `Task` schema for update operations excluding foreign keys and relations.
 */
export const TaskUpdateScalarSchema = baseSchema.partial();


/**
 * `Task` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const TaskUpdateSchema = TaskUpdateScalarSchema.merge(fkSchema.partial());

