/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { TodoState } from '../../../../generated/prisma_new_client/client';
import { TodoStateSchema } from '../enums/TodoState.schema';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean().default(false),
    orderTodo: z.number(),
    title: z.string(),
    content: z.string().nullish(),
    todoState: TodoStateSchema,
}
).strict();
const relationSchema = z.object({
    owner: z.record(z.unknown()),
    org: z.record(z.unknown()),
    groups: z.array(z.unknown()).optional(),
    mainTodo: z.record(z.unknown()).optional(),
    SubTodos: z.array(z.unknown()).optional(),
    Users: z.array(z.unknown()).optional(),
    Tasks: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    ownerId: z.string(),
    orgId: z.string(),
    mainTodoId: z.string().nullish(),
}
);

/**
 * `Todo` schema excluding foreign keys and relations.
 */
export const TodoScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Todo` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const TodoSchema = TodoScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const TodoPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const TodoPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    isPublic: z.boolean().default(false),
    orderTodo: z.union([z.number(), z.record(z.unknown())]),
    title: z.string(),
    content: z.string().nullish(),
    todoState: TodoStateSchema
}).partial().passthrough();


/**
 * `Todo` schema for create operations excluding foreign keys and relations.
 */
export const TodoCreateScalarSchema = baseSchema.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isDeleted: true, isPublic: true, todoState: true
});


/**
 * `Todo` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const TodoCreateSchema = TodoCreateScalarSchema.merge(fkSchema);


/**
 * `Todo` schema for update operations excluding foreign keys and relations.
 */
export const TodoUpdateScalarSchema = baseSchema.partial();


/**
 * `Todo` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const TodoUpdateSchema = TodoUpdateScalarSchema.merge(fkSchema.partial());

