/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type QueryContext, type CrudContract, type PermissionCheckerContext } from "@zenstackhq/runtime";
import { allFieldsEqual } from "@zenstackhq/runtime/validation";
import { type PolicyDef, type PermissionCheckerConstraint } from "@zenstackhq/runtime/enhancements/node";
import { TaskState } from "../generated/prisma_client/client";
import { TodoState } from "../generated/prisma_client/client";
import { Gender } from "../generated/prisma_client/client";
import { Title } from "../generated/prisma_client/client";
import { Language } from "../generated/prisma_client/client";
import { Role } from "../generated/prisma_client/client";
import { PermissionClaim } from "../generated/prisma_client/client";
import { TokenType } from "../generated/prisma_client/client";

const policy: PolicyDef = {
    policy: {
        organization: {
            modelLevel: {
                read: { guard: Organization_read, },
                create: { guard: Organization_create, },
                update: { guard: Organization_update, },
                postUpdate: { guard: Organization_postUpdate, },
                delete: { guard: Organization_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        orgEmail: {
            modelLevel: {
                read: { guard: OrgEmail_read, },
                create: { guard: OrgEmail_create, },
                update: { guard: OrgEmail_update, },
                postUpdate: { guard: OrgEmail_postUpdate, },
                delete: { guard: OrgEmail_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        orgDomain: {
            modelLevel: {
                read: { guard: OrgDomain_read, },
                create: { guard: OrgDomain_create, },
                update: { guard: OrgDomain_update, },
                postUpdate: { guard: OrgDomain_postUpdate, },
                delete: { guard: OrgDomain_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        user: {
            modelLevel: {
                read: { guard: User_read, },
                create: { guard: User_create, },
                update: { guard: User_update, },
                postUpdate: { guard: User_postUpdate, },
                delete: { guard: User_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        userSecret: {
            modelLevel: {
                read: { guard: UserSecret_read, },
                create: { guard: UserSecret_create, inputChecker: UserSecret_create_input, },
                update: { guard: UserSecret_update, },
                postUpdate: { guard: UserSecret_postUpdate, },
                delete: { guard: UserSecret_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        profile: {
            modelLevel: {
                read: { guard: Profile_read, },
                create: { guard: Profile_create, },
                update: { guard: Profile_update, },
                postUpdate: { guard: Profile_postUpdate, },
                delete: { guard: Profile_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        group: {
            modelLevel: {
                read: { guard: Group_read, },
                create: { guard: Group_create, },
                update: { guard: Group_update, },
                postUpdate: { guard: Group_postUpdate, },
                delete: { guard: Group_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        todo: {
            modelLevel: {
                read: { guard: Todo_read, },
                create: { guard: Todo_create, },
                update: { guard: Todo_update, },
                postUpdate: {
                    guard: Todo_postUpdate, preUpdateSelector: { "published": true, "owner": { "select": { "id": true } }, "org": { "select": { "Members": { "select": { "id": true } } } } },
                },
                delete: { guard: Todo_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        userTodoLink: {
            modelLevel: {
                read: { guard: UserTodoLink_read, },
                create: { guard: UserTodoLink_create, inputChecker: UserTodoLink_create_input, },
                update: { guard: UserTodoLink_update, },
                postUpdate: { guard: UserTodoLink_postUpdate, },
                delete: { guard: UserTodoLink_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        task: {
            modelLevel: {
                read: { guard: Task_read, },
                create: { guard: Task_create, },
                update: { guard: Task_update, },
                postUpdate: {
                    guard: Task_postUpdate, preUpdateSelector: { "published": true, "owner": { "select": { "id": true } }, "org": { "select": { "Members": { "select": { "id": true } } } } },
                },
                delete: { guard: Task_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        userTaskLink: {
            modelLevel: {
                read: { guard: UserTaskLink_read, },
                create: { guard: UserTaskLink_create, inputChecker: UserTaskLink_create_input, },
                update: { guard: UserTaskLink_update, },
                postUpdate: { guard: UserTaskLink_postUpdate, },
                delete: { guard: UserTaskLink_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        post: {
            modelLevel: {
                read: { guard: Post_read, },
                create: { guard: Post_create, },
                update: { guard: Post_update, },
                postUpdate: {
                    guard: Post_postUpdate, preUpdateSelector: { "published": true, "owner": { "select": { "id": true } }, "org": { "select": { "Members": { "select": { "id": true } } } } },
                },
                delete: { guard: Post_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        category: {
            modelLevel: {
                read: { guard: Category_read, },
                create: { guard: Category_create, },
                update: { guard: Category_update, },
                postUpdate: { guard: Category_postUpdate, },
                delete: { guard: Category_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        comment: {
            modelLevel: {
                read: { guard: Comment_read, },
                create: { guard: Comment_create, },
                update: { guard: Comment_update, },
                postUpdate: { guard: Comment_postUpdate, },
                delete: { guard: Comment_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        file: {
            modelLevel: {
                read: { guard: File_read, },
                create: { guard: File_create, },
                update: { guard: File_update, },
                postUpdate: {
                    guard: File_postUpdate, preUpdateSelector: { "published": true, "owner": { "select": { "id": true } }, "org": { "select": { "Members": { "select": { "id": true } } } } },
                },
                delete: { guard: File_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        userFollower: {
            modelLevel: {
                read: { guard: UserFollower_read, },
                create: { guard: UserFollower_create, inputChecker: UserFollower_create_input, },
                update: { guard: UserFollower_update, },
                postUpdate: { guard: UserFollower_postUpdate, },
                delete: { guard: UserFollower_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        postLike: {
            modelLevel: {
                read: { guard: PostLike_read, },
                create: { guard: PostLike_create, inputChecker: PostLike_create_input, },
                update: { guard: PostLike_update, },
                postUpdate: { guard: PostLike_postUpdate, },
                delete: { guard: PostLike_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        story: {
            modelLevel: {
                read: { guard: Story_read, },
                create: { guard: Story_create, },
                update: { guard: Story_update, },
                postUpdate: { guard: Story_postUpdate, },
                delete: { guard: Story_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        image: {
            modelLevel: {
                read: { guard: Image_read, },
                create: { guard: Image_create, },
                update: { guard: Image_update, },
                postUpdate: { guard: Image_postUpdate, },
                delete: { guard: Image_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        configParam: {
            modelLevel: {
                read: { guard: ConfigParam_read, },
                create: { guard: ConfigParam_create, },
                update: { guard: ConfigParam_update, },
                postUpdate: { guard: ConfigParam_postUpdate, },
                delete: { guard: ConfigParam_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        orgEmailUseTo: {
            modelLevel: {
                read: { guard: OrgEmailUseTo_read, },
                create: { guard: OrgEmailUseTo_create, },
                update: { guard: OrgEmailUseTo_update, },
                postUpdate: { guard: OrgEmailUseTo_postUpdate, },
                delete: { guard: OrgEmailUseTo_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        appEmailDomain: {
            modelLevel: {
                read: { guard: AppEmailDomain_read, },
                create: { guard: AppEmailDomain_create, },
                update: { guard: AppEmailDomain_update, },
                postUpdate: { guard: AppEmailDomain_postUpdate, },
                delete: { guard: AppEmailDomain_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        refreshToken: {
            modelLevel: {
                read: { guard: RefreshToken_read, },
                create: { guard: RefreshToken_create, },
                update: { guard: RefreshToken_update, },
                postUpdate: { guard: RefreshToken_postUpdate, },
                delete: { guard: RefreshToken_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        apiKey: {
            modelLevel: {
                read: { guard: ApiKey_read, },
                create: { guard: ApiKey_create, },
                update: { guard: ApiKey_update, },
                postUpdate: { guard: ApiKey_postUpdate, },
                delete: { guard: ApiKey_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        scope: {
            modelLevel: {
                read: { guard: Scope_read, },
                create: { guard: Scope_create, },
                update: { guard: Scope_update, },
                postUpdate: { guard: Scope_postUpdate, },
                delete: { guard: Scope_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        token: {
            modelLevel: {
                read: { guard: Token_read, },
                create: { guard: Token_create, },
                update: { guard: Token_update, },
                postUpdate: { guard: Token_postUpdate, },
                delete: { guard: Token_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        changesTracking: {
            modelLevel: {
                read: { guard: ChangesTracking_read, },
                create: { guard: ChangesTracking_create, },
                update: { guard: ChangesTracking_update, },
                postUpdate: { guard: ChangesTracking_postUpdate, },
                delete: { guard: ChangesTracking_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        accountValidation: {
            modelLevel: {
                read: { guard: AccountValidation_read, },
                create: { guard: AccountValidation_create, },
                update: { guard: AccountValidation_update, },
                postUpdate: { guard: AccountValidation_postUpdate, },
                delete: { guard: AccountValidation_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
    },
    validation: {
        organization: { hasValidation: true },
        orgEmail: { hasValidation: true },
        orgDomain: { hasValidation: false },
        user: { hasValidation: true },
        userSecret: { hasValidation: false },
        profile: { hasValidation: false },
        group: { hasValidation: false },
        todo: { hasValidation: false },
        userTodoLink: { hasValidation: false },
        task: { hasValidation: false },
        userTaskLink: { hasValidation: false },
        post: { hasValidation: false },
        category: { hasValidation: false },
        comment: { hasValidation: false },
        file: { hasValidation: false },
        userFollower: { hasValidation: false },
        postLike: { hasValidation: false },
        story: { hasValidation: false },
        image: { hasValidation: false },
        configParam: { hasValidation: false },
        orgEmailUseTo: { hasValidation: false },
        appEmailDomain: { hasValidation: false },
        refreshToken: { hasValidation: false },
        apiKey: { hasValidation: false },
        scope: { hasValidation: false },
        token: { hasValidation: false },
        changesTracking: { hasValidation: false },
        accountValidation: { hasValidation: false },
    },
    authSelector: { "id": true },
};

function Organization_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } }] }] };
}

function $check_Organization_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if ((((input?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) { return true; }

    return false;
}

function Organization_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user != null) ? { AND: [] } : { OR: [] }] };
}

function $check_Organization_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((user != null)) { return true; }

    return false;
}

function Organization_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Organization_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Organization_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Organization_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Organization_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Organization_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmail_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_OrgEmail_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmail_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgEmail_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmail_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgEmail_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmail_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrgEmail_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function OrgEmail_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgEmail_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgDomain_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_OrgDomain_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgDomain_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgDomain_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgDomain_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgDomain_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgDomain_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrgDomain_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function OrgDomain_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgDomain_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function User_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { Orgs: { some: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } } }, (user == null) ? { OR: [] } : { id: user.id }] }] };
}

function $check_User_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if ((((input?.Orgs)?.some((_item: any) => (((_item?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) ?? false)) { return true; }

    if (allFieldsEqual(user,
        input, ['id'])) { return true; }

    return false;
}

function User_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (true) { return true; }

    if (allFieldsEqual(user,
        input, ['id'])) { return true; }

    return false;
}

function User_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : { id: user.id }] };
}

function $check_User_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (allFieldsEqual(user,
        input, ['id'])) { return true; }

    return false;
}

function User_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function User_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : { id: user.id }] };
}

function $check_User_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (allFieldsEqual(user,
        input, ['id'])) { return true; }

    return false;
}

function UserSecret_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserSecret_read(input: any, context: QueryContext): any {
    return false;
}

function UserSecret_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserSecret_create(input: any, context: QueryContext): any {
    return false;
}

function UserSecret_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function UserSecret_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserSecret_update(input: any, context: QueryContext): any {
    return false;
}

function UserSecret_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_UserSecret_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function UserSecret_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserSecret_delete(input: any, context: QueryContext): any {
    return false;
}

function Profile_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Profile_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Profile_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Profile_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Profile_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Profile_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Profile_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Profile_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Profile_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Profile_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Group_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] }] };
}

function $check_Group_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if ((((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) { return true; }

    return false;
}

function Group_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] };
}

function $check_Group_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) { return true; }

    return false;
}

function Group_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] };
}

function $check_Group_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) { return true; }

    return false;
}

function Group_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Group_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Group_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] };
}

function $check_Group_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) { return true; }

    return false;
}

function Todo_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, {
            OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { groups: { some: { Users: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } } }, { AND: [{ isPublic: true }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] }]
        }]
    };
}

function $check_Todo_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    if ((((input?.groups)?.some((_item: any) => (((_item?.Users)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) ?? false)) { return true; }

    if ((input?.isPublic && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function Todo_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, {
            AND: [(user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }]
        }]
    };
}

function $check_Todo_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.owner?.id ?? null) == (user?.id ?? null)) && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function Todo_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Todo_update(input: any, context: QueryContext): any {
    return false;
}

function Todo_postUpdate(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { AND: [{ AND: [((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) ? { AND: [] } : { OR: [] }, ((((context.preValue?.org?.Members ?? null))?.some((_item: any) => (_item?.id == (user?.id ?? null)))) ?? false) ? { AND: [] } : { OR: [] }] }, { owner: { is: { id: context.preValue?.owner.id } } }] }] };
}

function $check_Todo_postUpdate(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && context.preValue?.published)) { return true; }

    if (((((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) && (((context.preValue?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) && ((input.owner?.id ?? null) == (context.preValue?.owner?.id ?? null)))) { return true; }

    return true;
}

function Todo_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
            owner: {
                is:
                    { id: user.id }
            }
        }]
    };
}

function $check_Todo_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    return false;
}

function UserTodoLink_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTodoLink_read(input: any, context: QueryContext): any {
    return false;
}

function UserTodoLink_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTodoLink_create(input: any, context: QueryContext): any {
    return false;
}

function UserTodoLink_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function UserTodoLink_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTodoLink_update(input: any, context: QueryContext): any {
    return false;
}

function UserTodoLink_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_UserTodoLink_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function UserTodoLink_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTodoLink_delete(input: any, context: QueryContext): any {
    return false;
}

function Task_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, {
            OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { groups: { some: { Users: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } } }, { AND: [{ isPublic: true }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] }]
        }]
    };
}

function $check_Task_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    if ((((input?.groups)?.some((_item: any) => (((_item?.Users)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) ?? false)) { return true; }

    if ((input?.isPublic && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function Task_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, {
            AND: [(user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }]
        }]
    };
}

function $check_Task_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.owner?.id ?? null) == (user?.id ?? null)) && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function Task_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Task_update(input: any, context: QueryContext): any {
    return false;
}

function Task_postUpdate(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { AND: [{ AND: [((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) ? { AND: [] } : { OR: [] }, ((((context.preValue?.org?.Members ?? null))?.some((_item: any) => (_item?.id == (user?.id ?? null)))) ?? false) ? { AND: [] } : { OR: [] }] }, { owner: { is: { id: context.preValue?.owner.id } } }] }] };
}

function $check_Task_postUpdate(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && context.preValue?.published)) { return true; }

    if (((((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) && (((context.preValue?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) && ((input.owner?.id ?? null) == (context.preValue?.owner?.id ?? null)))) { return true; }

    return true;
}

function Task_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
            owner: {
                is:
                    { id: user.id }
            }
        }]
    };
}

function $check_Task_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    return false;
}

function UserTaskLink_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTaskLink_read(input: any, context: QueryContext): any {
    return false;
}

function UserTaskLink_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTaskLink_create(input: any, context: QueryContext): any {
    return false;
}

function UserTaskLink_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function UserTaskLink_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTaskLink_update(input: any, context: QueryContext): any {
    return false;
}

function UserTaskLink_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_UserTaskLink_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function UserTaskLink_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserTaskLink_delete(input: any, context: QueryContext): any {
    return false;
}

function Post_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, {
            OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { groups: { some: { Users: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } } }, { AND: [{ isPublic: true }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] }]
        }]
    };
}

function $check_Post_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    if ((((input?.groups)?.some((_item: any) => (((_item?.Users)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) ?? false)) { return true; }

    if ((input?.isPublic && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function Post_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, {
            AND: [(user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }]
        }]
    };
}

function $check_Post_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.owner?.id ?? null) == (user?.id ?? null)) && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function Post_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Post_update(input: any, context: QueryContext): any {
    return false;
}

function Post_postUpdate(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { AND: [{ AND: [((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) ? { AND: [] } : { OR: [] }, ((((context.preValue?.org?.Members ?? null))?.some((_item: any) => (_item?.id == (user?.id ?? null)))) ?? false) ? { AND: [] } : { OR: [] }] }, { owner: { is: { id: context.preValue?.owner.id } } }] }] };
}

function $check_Post_postUpdate(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && context.preValue?.published)) { return true; }

    if (((((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) && (((context.preValue?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) && ((input.owner?.id ?? null) == (context.preValue?.owner?.id ?? null)))) { return true; }

    return true;
}

function Post_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
            owner: {
                is:
                    { id: user.id }
            }
        }]
    };
}

function $check_Post_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    return false;
}

function Category_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Category_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Category_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Category_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Category_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Category_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Category_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Category_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Category_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Category_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Comment_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Comment_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Comment_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Comment_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Comment_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Comment_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Comment_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Comment_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Comment_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Comment_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function File_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, {
            OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { groups: { some: { Users: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } } }, { AND: [{ isPublic: true }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }] }]
        }]
    };
}

function $check_File_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    if ((((input?.groups)?.some((_item: any) => (((_item?.Users)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) ?? false)) { return true; }

    if ((input?.isPublic && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function File_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, {
            AND: [(user == null) ? { OR: [] } : {
                owner: {
                    is:
                        { id: user.id }
                }
            }, { org: { Members: { some: ((user?.id ?? null) == null) ? { OR: [] } : { id: { equals: (user?.id ?? null) } } } } }]
        }]
    };
}

function $check_File_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if ((((input?.owner?.id ?? null) == (user?.id ?? null)) && (((input?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false))) { return true; }

    return false;
}

function File_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_File_update(input: any, context: QueryContext): any {
    return false;
}

function File_postUpdate(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, { AND: [{ AND: [((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) ? { AND: [] } : { OR: [] }, ((((context.preValue?.org?.Members ?? null))?.some((_item: any) => (_item?.id == (user?.id ?? null)))) ?? false) ? { AND: [] } : { OR: [] }] }, { owner: { is: { id: context.preValue?.owner.id } } }] }] };
}

function $check_File_postUpdate(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && context.preValue?.published)) { return true; }

    if (((((context.preValue?.owner?.id ?? null) == (user?.id ?? null)) && (((context.preValue?.org?.Members)?.some((_item: any) => (_item?.id == user?.id))) ?? false)) && ((input.owner?.id ?? null) == (context.preValue?.owner?.id ?? null)))) { return true; }

    return true;
}

function File_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return {
        OR: [{ AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }, (user == null) ? { OR: [] } : {
            owner: {
                is:
                    { id: user.id }
            }
        }]
    };
}

function $check_File_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    if (((input?.owner?.id ?? null) == (user?.id ?? null))) { return true; }

    return false;
}

function UserFollower_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserFollower_read(input: any, context: QueryContext): any {
    return false;
}

function UserFollower_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserFollower_create(input: any, context: QueryContext): any {
    return false;
}

function UserFollower_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function UserFollower_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserFollower_update(input: any, context: QueryContext): any {
    return false;
}

function UserFollower_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_UserFollower_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function UserFollower_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_UserFollower_delete(input: any, context: QueryContext): any {
    return false;
}

function PostLike_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PostLike_read(input: any, context: QueryContext): any {
    return false;
}

function PostLike_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PostLike_create(input: any, context: QueryContext): any {
    return false;
}

function PostLike_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function PostLike_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PostLike_update(input: any, context: QueryContext): any {
    return false;
}

function PostLike_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_PostLike_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function PostLike_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_PostLike_delete(input: any, context: QueryContext): any {
    return false;
}

function Story_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Story_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Story_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Story_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Story_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Story_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Story_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Story_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Story_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Story_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Image_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Image_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Image_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Image_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Image_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Image_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Image_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Image_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Image_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Image_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ConfigParam_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_ConfigParam_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ConfigParam_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ConfigParam_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ConfigParam_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ConfigParam_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ConfigParam_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_ConfigParam_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function ConfigParam_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ConfigParam_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmailUseTo_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_OrgEmailUseTo_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmailUseTo_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgEmailUseTo_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmailUseTo_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgEmailUseTo_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function OrgEmailUseTo_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrgEmailUseTo_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function OrgEmailUseTo_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_OrgEmailUseTo_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AppEmailDomain_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_AppEmailDomain_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AppEmailDomain_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_AppEmailDomain_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AppEmailDomain_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_AppEmailDomain_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AppEmailDomain_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_AppEmailDomain_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function AppEmailDomain_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_AppEmailDomain_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function RefreshToken_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_RefreshToken_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function RefreshToken_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_RefreshToken_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function RefreshToken_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_RefreshToken_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function RefreshToken_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_RefreshToken_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function RefreshToken_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_RefreshToken_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ApiKey_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_ApiKey_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ApiKey_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ApiKey_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ApiKey_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ApiKey_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ApiKey_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_ApiKey_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function ApiKey_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ApiKey_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Scope_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Scope_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Scope_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Scope_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Scope_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Scope_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Scope_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Scope_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Scope_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Scope_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Token_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_Token_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Token_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Token_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Token_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Token_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function Token_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Token_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Token_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_Token_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ChangesTracking_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_ChangesTracking_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ChangesTracking_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ChangesTracking_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ChangesTracking_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ChangesTracking_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function ChangesTracking_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_ChangesTracking_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function ChangesTracking_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_ChangesTracking_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AccountValidation_read(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [{ NOT: { isDeleted: { not: { equals: 0 } } } }, { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] }] };
}

function $check_AccountValidation_read(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if ((input?.isDeleted != 0)) { return false; }

    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AccountValidation_create(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_AccountValidation_create(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AccountValidation_update(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_AccountValidation_update(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}

function AccountValidation_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_AccountValidation_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function AccountValidation_delete(context: QueryContext, db: CrudContract): any {
    const user: any = context.user ?? null;
    return { AND: [(user != null) ? { AND: [] } : { OR: [] }, { published: true }] };
}

function $check_AccountValidation_delete(input: any, context: QueryContext): any {
    const user: any = context.user ?? null;
    if (((user != null) && input?.published)) { return true; }

    return false;
}
export default policy
