/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const TodoStateSchema = z.enum(["CREATION", "STANDBY", "RUNNING", "DONE"])
