/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.number().default(0).nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    orderCategory: z.number(),
    name: z.string(),
}
).strict();
const relationSchema = z.object({
    Posts: z.array(z.unknown()).optional(),
}
);

/**
 * `Category` schema excluding foreign keys and relations.
 */
export const CategoryScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Category` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const CategorySchema = CategoryScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const CategoryPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const CategoryPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.union([z.number().default(0).nullish(), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    orderCategory: z.union([z.number(), z.record(z.unknown())]),
    name: z.string()
}).partial().passthrough();


/**
 * `Category` schema for create operations excluding foreign keys and relations.
 */
export const CategoryCreateScalarSchema = baseSchema.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Category` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const CategoryCreateSchema = baseSchema.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Category` schema for update operations excluding foreign keys and relations.
 */
export const CategoryUpdateScalarSchema = baseSchema.partial();


/**
 * `Category` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const CategoryUpdateSchema = CategoryUpdateScalarSchema;

