/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    type: z.string(),
    url: z.string(),
    associated_id: z.string(),
    sequence: z.number(),
}
).strict();

/**
 * `Image` schema excluding foreign keys and relations.
 */
export const ImageScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Image` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ImageSchema = ImageScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ImagePrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ImagePrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    type: z.string(),
    url: z.string(),
    associated_id: z.string(),
    sequence: z.union([z.number(), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `Image` schema for create operations excluding foreign keys and relations.
 */
export const ImageCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Image` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ImageCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Image` schema for update operations excluding foreign keys and relations.
 */
export const ImageUpdateScalarSchema = baseSchema.partial();


/**
 * `Image` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ImageUpdateSchema = ImageUpdateScalarSchema;

