/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    useTo: z.string(),
    isActiv: z.boolean(),
}
).strict();
const relationSchema = z.object({
    emailOrg: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    emailOrgId: z.number(),
}
);

/**
 * `OrgEmailUseTo` schema excluding foreign keys and relations.
 */
export const OrgEmailUseToScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `OrgEmailUseTo` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const OrgEmailUseToSchema = OrgEmailUseToScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const OrgEmailUseToPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const OrgEmailUseToPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    useTo: z.string(),
    isActiv: z.boolean()
}).partial().passthrough();


/**
 * `OrgEmailUseTo` schema for create operations excluding foreign keys and relations.
 */
export const OrgEmailUseToCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `OrgEmailUseTo` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const OrgEmailUseToCreateSchema = OrgEmailUseToCreateScalarSchema.merge(fkSchema);


/**
 * `OrgEmailUseTo` schema for update operations excluding foreign keys and relations.
 */
export const OrgEmailUseToUpdateScalarSchema = baseSchema.partial();


/**
 * `OrgEmailUseTo` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const OrgEmailUseToUpdateSchema = OrgEmailUseToUpdateScalarSchema.merge(fkSchema.partial());

