/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.unknown()),
    post: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
}
);

/**
 * `PostLike` schema excluding foreign keys and relations.
 */
export const PostLikeScalarSchema = baseSchema;


/**
 * `PostLike` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const PostLikeSchema = PostLikeScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const PostLikePrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const PostLikePrismaUpdateSchema = z.object({
    user_id: z.string(),
    post_id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date())
}).partial().passthrough();


/**
 * `PostLike` schema for create operations excluding foreign keys and relations.
 */
export const PostLikeCreateScalarSchema = baseSchema.partial({
    createdAt: true, updatedAt: true
});


/**
 * `PostLike` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const PostLikeCreateSchema = PostLikeCreateScalarSchema.merge(fkSchema);


/**
 * `PostLike` schema for update operations excluding foreign keys and relations.
 */
export const PostLikeUpdateScalarSchema = baseSchema.partial();


/**
 * `PostLike` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const PostLikeUpdateSchema = PostLikeUpdateScalarSchema.merge(fkSchema.partial());

