/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    scope: z.string(),
}
).strict();
const relationSchema = z.object({
    ApiKey: z.array(z.unknown()).optional(),
}
);

/**
 * `Scope` schema excluding foreign keys and relations.
 */
export const ScopeScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Scope` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ScopeSchema = ScopeScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ScopePrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ScopePrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    scope: z.string()
}).partial().passthrough();


/**
 * `Scope` schema for create operations excluding foreign keys and relations.
 */
export const ScopeCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Scope` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ScopeCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true
});


/**
 * `Scope` schema for update operations excluding foreign keys and relations.
 */
export const ScopeUpdateScalarSchema = baseSchema.partial();


/**
 * `Scope` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ScopeUpdateSchema = ScopeUpdateScalarSchema;

