/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { TokenTypeSchema } from '../enums/TokenType.schema';
const baseSchema = z.object({
    id: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.number().default(0),
    isDeletedDT: z.coerce.date().nullish(),
    tokenId: z.string().nullish(),
    type: TokenTypeSchema,
    emailToken: z.string().nullish(),
    valid: z.boolean().default(true),
    expiration: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    user: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    userId: z.string(),
}
);

/**
 * `Token` schema excluding foreign keys and relations.
 */
export const TokenScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `Token` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const TokenSchema = TokenScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const TokenPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const TokenPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(true),
    isPublic: z.boolean().default(true),
    isDeleted: z.union([z.number().default(0), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    tokenId: z.string().nullish(),
    type: TokenTypeSchema,
    emailToken: z.string().nullish(),
    valid: z.boolean().default(true),
    expiration: z.coerce.date()
}).partial().passthrough();


/**
 * `Token` schema for create operations excluding foreign keys and relations.
 */
export const TokenCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true, valid: true
});


/**
 * `Token` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const TokenCreateSchema = TokenCreateScalarSchema.merge(fkSchema);


/**
 * `Token` schema for update operations excluding foreign keys and relations.
 */
export const TokenUpdateScalarSchema = baseSchema.partial();


/**
 * `Token` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const TokenUpdateSchema = TokenUpdateScalarSchema.merge(fkSchema.partial());

