/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { Gender, Language } from '../../../../generated/prisma_client/client';
import { TitleSchema } from '../enums/Title.schema';
import { GenderSchema } from '../enums/Gender.schema';
import { LanguageSchema } from '../enums/Language.schema';
import { RoleSchema } from '../enums/Role.schema';
import { PermissionClaimSchema } from '../enums/PermissionClaim.schema';
const baseSchema = z.object({
    id: z.string(),
    numSeq: z.number(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.number().default(0).nullish(),
    isDeletedDT: z.coerce.date().nullish(),
    email: z.string().email(),
    lastName: z.string().nullish(),
    firstName: z.string().nullish(),
    title: TitleSchema.nullish(),
    nickName: z.string().nullish(),
    Gender: GenderSchema.nullish(),
    social: z.any().nullish(),
    Language: LanguageSchema.nullish(),
    photoUrl: z.string().nullish(),
    dob: z.coerce.date().nullish(),
    address: z.any().nullish(),
    isValidated: z.coerce.date().nullish(),
    isSuspended: z.coerce.date().nullish(),
    Roles: z.array(RoleSchema),
    Permissions: z.array(PermissionClaimSchema),
    isTfaEnable: z.boolean().default(false),
    tfaSecret: z.string().nullish(),
    passWordFaker: z.string().nullish(),
}
).strict();
const relationSchema = z.object({
    Orgs: z.array(z.unknown()).optional(),
    manager: z.record(z.unknown()).optional(),
    Team: z.array(z.unknown()).optional(),
    Profiles: z.array(z.unknown()).optional(),
    Groups: z.array(z.unknown()).optional(),
    Posts: z.array(z.unknown()).optional(),
    Comments: z.array(z.unknown()).optional(),
    Stories: z.array(z.unknown()).optional(),
    Todo: z.array(z.unknown()).optional(),
    TodosAuthor: z.array(z.unknown()).optional(),
    Tasks: z.array(z.unknown()).optional(),
    TasksAuthor: z.array(z.unknown()).optional(),
    Files: z.array(z.unknown()).optional(),
    ChangesLogs: z.array(z.unknown()).optional(),
    Tokens: z.array(z.unknown()).optional(),
    ApiKeys: z.array(z.unknown()).optional(),
    userSecret: z.record(z.unknown()).optional(),
    followers: z.array(z.unknown()).optional(),
    followings: z.array(z.unknown()).optional(),
    posts_liked: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    managerId: z.string().nullish(),
}
);

/**
 * `User` schema excluding foreign keys and relations.
 */
export const UserScalarSchema = baseSchema.omit({
    isDeleted: true,
});


/**
 * `User` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const UserSchema = UserScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const UserPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const UserPrismaUpdateSchema = z.object({
    id: z.string(),
    numSeq: z.union([z.number(), z.record(z.unknown())]),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date().default(() => new Date()),
    published: z.boolean().default(false).nullish(),
    isPublic: z.boolean().default(true).nullish(),
    isDeleted: z.union([z.number().default(0).nullish(), z.record(z.unknown())]),
    isDeletedDT: z.coerce.date().nullish(),
    email: z.string().email(),
    lastName: z.string().nullish(),
    firstName: z.string().nullish(),
    title: TitleSchema.nullish(),
    nickName: z.string().nullish(),
    Gender: GenderSchema.nullish(),
    social: z.any().nullish(),
    Language: LanguageSchema.nullish(),
    photoUrl: z.string().nullish(),
    dob: z.coerce.date().nullish(),
    address: z.any().nullish(),
    isValidated: z.coerce.date().nullish(),
    isSuspended: z.coerce.date().nullish(),
    Roles: z.array(RoleSchema),
    Permissions: z.array(PermissionClaimSchema),
    isTfaEnable: z.boolean().default(false),
    tfaSecret: z.string().nullish(),
    passWordFaker: z.string().nullish()
}).partial().passthrough();


/**
 * `User` schema for create operations excluding foreign keys and relations.
 */
export const UserCreateScalarSchema = baseSchema.partial({
    id: true, numSeq: true, createdAt: true, updatedAt: true, published: true, isPublic: true, isDeleted: true, Gender: true, Language: true, Roles: true, Permissions: true, isTfaEnable: true
});


/**
 * `User` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const UserCreateSchema = UserCreateScalarSchema.merge(fkSchema);


/**
 * `User` schema for update operations excluding foreign keys and relations.
 */
export const UserUpdateScalarSchema = baseSchema.partial();


/**
 * `User` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const UserUpdateSchema = UserUpdateScalarSchema.merge(fkSchema.partial());

