/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const FileScalarFieldEnumSchema = z.enum(["id", "numSeq", "createdAt", "updatedAt", "published", "isDeleted", "isDeletedDT", "isPublic", "ownerId", "orgId", "name", "storageName", "type", "data", "size", "isArchived"])
