/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const TodoScalarFieldEnumSchema = z.enum(["id", "numSeq", "createdAt", "updatedAt", "published", "isDeleted", "isDeletedDT", "isPublic", "ownerId", "orgId", "orderTodo", "title", "content", "todoState", "mainTodoId"])
