/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const UserTaskLinkScalarFieldEnumSchema = z.enum(["userId", "taskId", "isAuthor", "isAssigned", "createdAt", "updatedAt", "comment"])
