/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const GenderSchema = z.enum(["MALE", "FEMELE", "UNKNOWN", "NONE"])
