/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';

export const JsonNullValueFilterSchema = z.enum(["DbNull", "JsonNull", "AnyNull"])
