/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const NullsOrderSchema = z.enum(["first", "last"])
