/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const NullableJsonNullValueInputSchema = z.enum(["DbNull", "JsonNull"])
