/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const PermissionClaimSchema = z.enum(["CreateCoffee", "UpdateCoffee", "DeleteCoffee"])
