/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const PositionSchema = z.enum(["Manager", "Member", "Secretary"])
