/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const PostLikeScalarFieldEnumSchema = z.enum(["user_id", "post_id", "createdAt", "updatedAt"])
