/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const RoleSchema = z.enum(["GUEST", "USER", "ADMIN", "SUPERADMIN", "REGULAR"])
