/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';

export const TitleSchema = z.enum(["Mr", "Mme", "Dct"])
