/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const TokenTypeSchema = z.enum(["EMAIL", "API", "FORGOT", "ACCOUNT", "REFREZH"])
