/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const UserFollowerScalarFieldEnumSchema = z.enum(["user_id", "follower_id", "createdAt", "updatedAt"])
