/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const UserTodoLinkScalarFieldEnumSchema = z.enum(["userId", "todoId", "isAuthor", "isAssigned", "createdAt", "updatedAt", "comment"])
