/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod';

export const UserSecretScalarFieldEnumSchema = z.enum(["id", "createdAt", "updatedAt", "userId", "pwdHash", "salt", "isAdmin"])
