/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import { z } from 'zod/v3';

export const UserTaskLinkScalarFieldEnumSchema = z.enum(["userId", "taskId", "isAuthor", "isAssigned", "createdAt", "updatedAt", "comment"])
